# Generated by Django 4.2.16 on 2024-09-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('kazakh', 'Қазақша'), ('russian', 'Русский'), ('english', 'English')], default='english', max_length=10),
        ),
    ]
