# Generated by Django 4.2.16 on 2024-09-08 10:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_clubmembershiprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubpost',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
